# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0

name: Build & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: eclipse-opensovd/cicd-workflows/.github/workflows/build-and-test.yml@fef5cc7b2d4c4c6593b105402fbf4edd54db7d5a
    with:
      rust-version: "nightly-2025-07-14"
      cargo-locked: true
      cargo-test-args: "--workspace --all-targets"
      bazel-enabled: true
      bazel-build-targets: "//src/... //tests/..."
      bazel-test-targets: "//src/... //tests/..."
